version: '3'

services:

  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ssuser
      - POSTGRES_PASSWORD=ThisShouldBeASecretDev
      - POSTGRES_DB=sswebsite_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/sswebsite
    ports:
      - "8000:8000"
    env_file: .env.dev
    depends_on:
      - db


volumes:
  postgres_data:

