# Generated by Django 3.0.7 on 2020-07-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdev',
            name='intro_phone_left',
        ),
        migrations.RemoveField(
            model_name='webdev',
            name='intro_phone_right',
        ),
    ]
