# Generated by Django 3.0.7 on 2020-07-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0003_webdevproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdevproject',
            name='summary',
            field=models.TextField(),
        ),
    ]
