# Generated by Django 3.0.7 on 2020-07-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0009_auto_20200719_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdevproject',
            name='web_url',
            field=models.URLField(blank=True),
        ),
    ]
