# Generated by Django 3.0.7 on 2020-06-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('bio_title', models.CharField(max_length=255)),
                ('bio_paragraph1', models.CharField(max_length=255)),
                ('bio_paragraph2', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('contact_facebook', models.URLField(blank=True, verbose_name='Facebook')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
