# Generated by Django 3.0.7 on 2020-06-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('photography', '0002_photographyalbum_title_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='default_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
